default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: instante_development
  host: localhost
  port: 5432
test:
  <<: *default
  adapter: postgresql
  database: instante_test
production:
  <<: *default
  adapter: postgresql
  database: instante_production
  username: instante
  password: <%= ENV['INSTANTE_DATABASE_PASSWORD'] %>
